joint_states: "/placeholder"

publish_rate: 100.0

joint_names: ["x_joint", "y_joint", "z_joint", "roll_joint", "pitch_joint", "yaw_joint"]

p_gain_roll: 0.4
i_gain_roll: 0
d_gain_roll: 0.1
i_max_roll: 100
i_min_roll: -100
anti_windup_roll: true

p_gain_pitch: 0.4
i_gain_pitch: 0
d_gain_pitch: 0.1
i_max_pitch: 100
i_min_pitch: -100
anti_windup_pitch: true

p_gain_yaw: 2
i_gain_yaw: 0
d_gain_yaw: 0.2
i_max_yaw: 100
i_min_yaw: -100
anti_windup_yaw: true

p_gain_x: 1
i_gain_x: 0
d_gain_x: 0.2
i_max_x: 100
i_min_x: -100
anti_windup_x: true

p_gain_y: 1
i_gain_y: 0
d_gain_y: 0.2
i_max_y: 100
i_min_y: -100
anti_windup_y: true

p_gain_z: 1
i_gain_z: 0
d_gain_z: 0.2
i_max_z: 100
i_min_z: -100
anti_windup_z: true

position_limit_roll: 0.35
position_limit_pitch: 0.35
position_limit_yaw: 6.3
position_limit_x: 5000
position_limit_y: 5000
position_limit_z: 5000

velocity_limit_roll: 2
velocity_limit_pitch: 2
velocity_limit_yaw: 3
velocity_limit_x: 3.0
velocity_limit_y: 3.0
velocity_limit_z: 3.0